name: Test Docker Build and Run

on:
  push:
    branches:
      - main  # or change to any branch you want

jobs:
  test-docker-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image (no push)
      run: |
        docker build -t test-image:latest .

    - name: Run Docker container
      run: |
        docker run -d -p 3000:3000 test-image:latest

    - name: Wait for app to start
      run: |
        sleep 5  # Wait for the container to fully start

    - name: Test the app with curl
      run: |
        curl http://localhost:3000
